[auth]
enabled = true
site_url = "https://devflow-cravey7s-projects.vercel.app/"
additional_redirect_urls = [
  "https://devflow-cravey7s-projects.vercel.app/",
  "https://devflow-cravey7s-projects.vercel.app/**",
  "https://devflow-*-cravey7s-projects.vercel.app",
  "https://devflow-*-cravey7s-projects.vercel.app/**",
  "https://devflow-cravey7-cravey7s-projects.vercel.app/",
  "https://devflow-cravey7-cravey7s-projects.vercel.app/**",
  "https://devflow-*-cravey7-cravey7s-projects.vercel.app",
  "https://devflow-*-cravey7-cravey7s-projects.vercel.app/**"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10

[auth.mfa]
max_enrolled_factors = 10

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
secure_password_change = false
max_frequency = "1m0s"
otp_length = 6 