import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  Github,
  HelpCircle,
  Image,
  Laptop,
  Loader2,
  LucideProps,
  Moon,
  MoreVertical,
  Pizza,
  Plus,
  RefreshCw,
  Settings,
  SunMedium,
  Trash,
  Twitter,
  User,
  X,
  Mail,
  type Icon as LucideIcon,
  AlertCircle,
  CheckCircle2,
  Chrome,
  Facebook,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  logo: Chrome,
  close: X,
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  post: FileText,
  page: File,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  pizza: Pizza,
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  gitHub: Github,
  twitter: Twitter,
  check: Check,
  google: Chrome,
  refresh: RefreshCw,
  mail: Mail,
  alert: AlertCircle,
  check: CheckCircle2,
  facebook: Facebook,
} 